import Head from 'next/head'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
import Users from "../components/Users";
import {useEffect, useState} from "react";




export default function Home() {

    const [allUsers, setAllUser] = useState([]);
    const [filteredUser, setFilterUser] = useState([]);
    const [filter, setFilter] = useState({
        s: '',
        sort: '',
        page: 1
    });
    const [lastPage, setLastPage] = useState(0);
    const perPage = 9;

    useEffect(() => {
        (
            async () => {
                const response = await fetch('http://127.0.0.1:8000/api/users/frontend')
                const content = await response.json();

                setAllUser(content);
                setFilterUser(content.slice(0, filter.page * perPage));
                setLastPage(Math.ceil(content.length / perPage));
            }
        )()
    }, [])

    useEffect(() => {
        let users = allUsers.filter(p => p.name.toLowerCase().indexOf(filter.s.toLowerCase()) >= 0 ||
            p.email.toLowerCase().indexOf(filter.s.toLowerCase()) >= 0 )

        if (filter.sort === 'asc' || filter.sort === 'desc'){
            users.sort((a,b) => {
                const diff = a.age - b.age

                if (diff === 0) return 0;

                const sign = Math.abs(diff) / diff;

                return filter.sort === 'asc' ? sign : -sign ;
            })
        }


        setLastPage(Math.ceil(users.length / perPage));
        setFilterUser(users.slice(0, filter.page * perPage));

    }, [filter]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Layout>
          <Users users={filteredUser}  filter={filter} setFilter={setFilter}  lastPage={lastPage}/>
      </Layout>


    </div>
  )
}
